spring:
  cloud:
    gateway:
      routes:
        - id: after_route
          uri: https://example.org
          predicates:
            - Cookie=mycookie,mycookievalue
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
            - Before=2017-01-20T17:42:47.789-07:00[America/Denver]

