server:
  port: ${server_port:8888}
management:
  endpoint:
    web:
      exposure:
        include: "*"
spring:
  cloud:
    gateway:
      enabled: true
      routes:
        - id: path_route
          uri: https://example.org
          predicates:
            - Path=/red/**


